import { Forecastday } from "../../api/types";

export const forecasts: Forecastday[] = [
    {
        "date": "2024-06-06",
        "date_epoch": 1717632000,
        "day": {
            "maxtemp_c": 17.5,
            "maxtemp_f": 63.4,
            "mintemp_c": 9.6,
            "mintemp_f": 49.2,
            "avgtemp_c": 13.5,
            "avgtemp_f": 56.4,
            "maxwind_mph": 8.9,
            "maxwind_kph": 14.4,
            "totalprecip_mm": 1.12,
            "totalprecip_in": 0.04,
            "totalsnow_cm": 0.0,
            "avgvis_km": 10.0,
            "avgvis_miles": 6.0,
            "avghumidity": 63,
            "daily_will_it_rain": 1,
            "daily_chance_of_rain": 89,
            "daily_will_it_snow": 0,
            "daily_chance_of_snow": 0,
            "condition": {
                "text": "Patchy rain nearby",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                "code": 1063
            },
            "uv": 5.0
        },
        "astro": {
            "sunrise": "04:45 AM",
            "sunset": "09:14 PM",
            "moonrise": "04:02 AM",
            "moonset": "10:02 PM",
            "moon_phase": "New Moon",
            "moon_illumination": 0,
            "is_moon_up": 0,
            "is_sun_up": 0
        },
        "hour": [
            {
                "time_epoch": 1717628400,
                "time": "2024-06-06 00:00",
                "temp_c": 10.9,
                "temp_f": 51.7,
                "is_day": 0,
                "condition": {
                    "text": "Partly Cloudy ",
                    "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                    "code": 1003
                },
                "wind_mph": 5.4,
                "wind_kph": 8.6,
                "wind_degree": 271,
                "wind_dir": "W",
                "pressure_mb": 1016.0,
                "pressure_in": 30.01,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 74,
                "cloud": 49,
                "feelslike_c": 10.0,
                "feelslike_f": 50.0,
                "windchill_c": 10.0,
                "windchill_f": 50.0,
                "heatindex_c": 10.9,
                "heatindex_f": 51.7,
                "dewpoint_c": 6.5,
                "dewpoint_f": 43.6,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 8.0,
                "gust_kph": 12.9,
                "uv": 1.0
            },
            {
                "time_epoch": 1717632000,
                "time": "2024-06-06 01:00",
                "temp_c": 10.4,
                "temp_f": 50.7,
                "is_day": 0,
                "condition": {
                    "text": "Overcast ",
                    "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                    "code": 1009
                },
                "wind_mph": 4.7,
                "wind_kph": 7.6,
                "wind_degree": 272,
                "wind_dir": "W",
                "pressure_mb": 1016.0,
                "pressure_in": 30.0,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 76,
                "cloud": 100,
                "feelslike_c": 9.5,
                "feelslike_f": 49.2,
                "windchill_c": 9.5,
                "windchill_f": 49.2,
                "heatindex_c": 10.4,
                "heatindex_f": 50.7,
                "dewpoint_c": 6.3,
                "dewpoint_f": 43.4,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 7.2,
                "gust_kph": 11.6,
                "uv": 1.0
            },
            {
                "time_epoch": 1717635600,
                "time": "2024-06-06 02:00",
                "temp_c": 10.1,
                "temp_f": 50.1,
                "is_day": 0,
                "condition": {
                    "text": "Overcast ",
                    "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                    "code": 1009
                },
                "wind_mph": 4.9,
                "wind_kph": 7.9,
                "wind_degree": 265,
                "wind_dir": "W",
                "pressure_mb": 1016.0,
                "pressure_in": 30.0,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 76,
                "cloud": 100,
                "feelslike_c": 9.1,
                "feelslike_f": 48.4,
                "windchill_c": 9.1,
                "windchill_f": 48.4,
                "heatindex_c": 10.1,
                "heatindex_f": 50.1,
                "dewpoint_c": 6.0,
                "dewpoint_f": 42.9,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 7.4,
                "gust_kph": 12.0,
                "uv": 1.0
            },
            {
                "time_epoch": 1717639200,
                "time": "2024-06-06 03:00",
                "temp_c": 9.8,
                "temp_f": 49.7,
                "is_day": 0,
                "condition": {
                    "text": "Patchy rain nearby",
                    "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                    "code": 1063
                },
                "wind_mph": 4.3,
                "wind_kph": 6.8,
                "wind_degree": 253,
                "wind_dir": "WSW",
                "pressure_mb": 1015.0,
                "pressure_in": 29.99,
                "precip_mm": 0.01,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 79,
                "cloud": 100,
                "feelslike_c": 9.1,
                "feelslike_f": 48.4,
                "windchill_c": 9.1,
                "windchill_f": 48.4,
                "heatindex_c": 9.9,
                "heatindex_f": 49.7,
                "dewpoint_c": 6.3,
                "dewpoint_f": 43.4,
                "will_it_rain": 0,
                "chance_of_rain": 60,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 6.7,
                "gust_kph": 10.8,
                "uv": 1.0
            },
            {
                "time_epoch": 1717642800,
                "time": "2024-06-06 04:00",
                "temp_c": 9.6,
                "temp_f": 49.2,
                "is_day": 0,
                "condition": {
                    "text": "Overcast ",
                    "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                    "code": 1009
                },
                "wind_mph": 4.3,
                "wind_kph": 6.8,
                "wind_degree": 252,
                "wind_dir": "WSW",
                "pressure_mb": 1016.0,
                "pressure_in": 29.99,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 79,
                "cloud": 100,
                "feelslike_c": 8.8,
                "feelslike_f": 47.8,
                "windchill_c": 8.8,
                "windchill_f": 47.8,
                "heatindex_c": 9.6,
                "heatindex_f": 49.2,
                "dewpoint_c": 6.1,
                "dewpoint_f": 43.0,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 6.7,
                "gust_kph": 10.8,
                "uv": 1.0
            },
            {
                "time_epoch": 1717646400,
                "time": "2024-06-06 05:00",
                "temp_c": 9.9,
                "temp_f": 49.9,
                "is_day": 1,
                "condition": {
                    "text": "Partly Cloudy ",
                    "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                    "code": 1003
                },
                "wind_mph": 5.1,
                "wind_kph": 8.3,
                "wind_degree": 253,
                "wind_dir": "WSW",
                "pressure_mb": 1016.0,
                "pressure_in": 30.0,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 75,
                "cloud": 27,
                "feelslike_c": 8.9,
                "feelslike_f": 47.9,
                "windchill_c": 8.9,
                "windchill_f": 47.9,
                "heatindex_c": 9.9,
                "heatindex_f": 49.9,
                "dewpoint_c": 5.8,
                "dewpoint_f": 42.4,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 7.4,
                "gust_kph": 12.0,
                "uv": 3.0
            },
            {
                "time_epoch": 1717650000,
                "time": "2024-06-06 06:00",
                "temp_c": 11.0,
                "temp_f": 51.9,
                "is_day": 1,
                "condition": {
                    "text": "Patchy rain nearby",
                    "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                    "code": 1063
                },
                "wind_mph": 6.0,
                "wind_kph": 9.7,
                "wind_degree": 256,
                "wind_dir": "WSW",
                "pressure_mb": 1016.0,
                "pressure_in": 30.01,
                "precip_mm": 0.01,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 68,
                "cloud": 88,
                "feelslike_c": 9.9,
                "feelslike_f": 49.8,
                "windchill_c": 9.9,
                "windchill_f": 49.8,
                "heatindex_c": 11.0,
                "heatindex_f": 51.9,
                "dewpoint_c": 5.4,
                "dewpoint_f": 41.8,
                "will_it_rain": 1,
                "chance_of_rain": 89,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 7.8,
                "gust_kph": 12.5,
                "uv": 3.0
            },
            {
                "time_epoch": 1717653600,
                "time": "2024-06-06 07:00",
                "temp_c": 12.5,
                "temp_f": 54.5,
                "is_day": 1,
                "condition": {
                    "text": "Sunny",
                    "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                    "code": 1000
                },
                "wind_mph": 6.5,
                "wind_kph": 10.4,
                "wind_degree": 261,
                "wind_dir": "W",
                "pressure_mb": 1017.0,
                "pressure_in": 30.02,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 62,
                "cloud": 21,
                "feelslike_c": 11.5,
                "feelslike_f": 52.8,
                "windchill_c": 11.5,
                "windchill_f": 52.8,
                "heatindex_c": 12.5,
                "heatindex_f": 54.5,
                "dewpoint_c": 5.4,
                "dewpoint_f": 41.7,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 7.6,
                "gust_kph": 12.2,
                "uv": 4.0
            },
            {
                "time_epoch": 1717657200,
                "time": "2024-06-06 08:00",
                "temp_c": 13.9,
                "temp_f": 57.0,
                "is_day": 1,
                "condition": {
                    "text": "Patchy rain nearby",
                    "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                    "code": 1063
                },
                "wind_mph": 6.9,
                "wind_kph": 11.2,
                "wind_degree": 266,
                "wind_dir": "W",
                "pressure_mb": 1017.0,
                "pressure_in": 30.02,
                "precip_mm": 0.01,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 57,
                "cloud": 78,
                "feelslike_c": 13.1,
                "feelslike_f": 55.7,
                "windchill_c": 13.1,
                "windchill_f": 55.7,
                "heatindex_c": 13.9,
                "heatindex_f": 57.0,
                "dewpoint_c": 5.7,
                "dewpoint_f": 42.2,
                "will_it_rain": 1,
                "chance_of_rain": 75,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 8.0,
                "gust_kph": 12.9,
                "uv": 3.0
            },
            {
                "time_epoch": 1717660800,
                "time": "2024-06-06 09:00",
                "temp_c": 15.1,
                "temp_f": 59.1,
                "is_day": 1,
                "condition": {
                    "text": "Patchy rain nearby",
                    "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                    "code": 1063
                },
                "wind_mph": 7.2,
                "wind_kph": 11.5,
                "wind_degree": 268,
                "wind_dir": "W",
                "pressure_mb": 1017.0,
                "pressure_in": 30.02,
                "precip_mm": 0.06,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 53,
                "cloud": 76,
                "feelslike_c": 15.1,
                "feelslike_f": 59.1,
                "windchill_c": 15.1,
                "windchill_f": 59.1,
                "heatindex_c": 15.1,
                "heatindex_f": 59.1,
                "dewpoint_c": 5.6,
                "dewpoint_f": 42.0,
                "will_it_rain": 1,
                "chance_of_rain": 100,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 8.2,
                "gust_kph": 13.2,
                "uv": 4.0
            },
            {
                "time_epoch": 1717664400,
                "time": "2024-06-06 10:00",
                "temp_c": 15.5,
                "temp_f": 60.0,
                "is_day": 1,
                "condition": {
                    "text": "Patchy rain nearby",
                    "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                    "code": 1063
                },
                "wind_mph": 8.3,
                "wind_kph": 13.3,
                "wind_degree": 273,
                "wind_dir": "W",
                "pressure_mb": 1017.0,
                "pressure_in": 30.03,
                "precip_mm": 0.06,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 51,
                "cloud": 66,
                "feelslike_c": 15.5,
                "feelslike_f": 60.0,
                "windchill_c": 15.5,
                "windchill_f": 60.0,
                "heatindex_c": 15.5,
                "heatindex_f": 60.0,
                "dewpoint_c": 5.5,
                "dewpoint_f": 42.0,
                "will_it_rain": 1,
                "chance_of_rain": 100,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 9.5,
                "gust_kph": 15.3,
                "uv": 4.0
            },
            {
                "time_epoch": 1717668000,
                "time": "2024-06-06 11:00",
                "temp_c": 16.5,
                "temp_f": 61.7,
                "is_day": 1,
                "condition": {
                    "text": "Patchy rain nearby",
                    "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                    "code": 1063
                },
                "wind_mph": 8.9,
                "wind_kph": 14.4,
                "wind_degree": 274,
                "wind_dir": "W",
                "pressure_mb": 1017.0,
                "pressure_in": 30.03,
                "precip_mm": 0.06,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 48,
                "cloud": 67,
                "feelslike_c": 16.5,
                "feelslike_f": 61.7,
                "windchill_c": 16.5,
                "windchill_f": 61.7,
                "heatindex_c": 16.5,
                "heatindex_f": 61.7,
                "dewpoint_c": 5.5,
                "dewpoint_f": 41.9,
                "will_it_rain": 1,
                "chance_of_rain": 100,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 10.4,
                "gust_kph": 16.7,
                "uv": 4.0
            },
            {
                "time_epoch": 1717671600,
                "time": "2024-06-06 12:00",
                "temp_c": 17.0,
                "temp_f": 62.6,
                "is_day": 1,
                "condition": {
                    "text": "Patchy rain nearby",
                    "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                    "code": 1063
                },
                "wind_mph": 8.1,
                "wind_kph": 13.0,
                "wind_degree": 279,
                "wind_dir": "W",
                "pressure_mb": 1017.0,
                "pressure_in": 30.04,
                "precip_mm": 0.03,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 46,
                "cloud": 65,
                "feelslike_c": 17.0,
                "feelslike_f": 62.6,
                "windchill_c": 17.0,
                "windchill_f": 62.6,
                "heatindex_c": 17.0,
                "heatindex_f": 62.6,
                "dewpoint_c": 5.3,
                "dewpoint_f": 41.5,
                "will_it_rain": 0,
                "chance_of_rain": 70,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 9.3,
                "gust_kph": 14.9,
                "uv": 4.0
            },
            {
                "time_epoch": 1717675200,
                "time": "2024-06-06 13:00",
                "temp_c": 17.5,
                "temp_f": 63.4,
                "is_day": 1,
                "condition": {
                    "text": "Patchy rain nearby",
                    "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                    "code": 1063
                },
                "wind_mph": 8.1,
                "wind_kph": 13.0,
                "wind_degree": 280,
                "wind_dir": "W",
                "pressure_mb": 1017.0,
                "pressure_in": 30.03,
                "precip_mm": 0.08,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 46,
                "cloud": 58,
                "feelslike_c": 17.5,
                "feelslike_f": 63.4,
                "windchill_c": 17.5,
                "windchill_f": 63.4,
                "heatindex_c": 17.5,
                "heatindex_f": 63.4,
                "dewpoint_c": 5.7,
                "dewpoint_f": 42.2,
                "will_it_rain": 1,
                "chance_of_rain": 100,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 9.3,
                "gust_kph": 14.9,
                "uv": 4.0
            },
            {
                "time_epoch": 1717678800,
                "time": "2024-06-06 14:00",
                "temp_c": 17.0,
                "temp_f": 62.6,
                "is_day": 1,
                "condition": {
                    "text": "Sunny",
                    "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                    "code": 1000
                },
                "wind_mph": 10.5,
                "wind_kph": 16.9,
                "wind_degree": 230,
                "wind_dir": "SW",
                "pressure_mb": 1018.0,
                "pressure_in": 30.06,
                "precip_mm": 0.07,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 45,
                "cloud": 0,
                "feelslike_c": 16.8,
                "feelslike_f": 62.2,
                "windchill_c": 16.8,
                "windchill_f": 62.2,
                "heatindex_c": 16.8,
                "heatindex_f": 62.2,
                "dewpoint_c": 6.4,
                "dewpoint_f": 43.4,
                "will_it_rain": 1,
                "chance_of_rain": 100,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 15.0,
                "gust_kph": 24.1,
                "uv": 4.0
            },
            {
                "time_epoch": 1717682400,
                "time": "2024-06-06 15:00",
                "temp_c": 17.0,
                "temp_f": 62.7,
                "is_day": 1,
                "condition": {
                    "text": "Light rain shower",
                    "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
                    "code": 1240
                },
                "wind_mph": 7.6,
                "wind_kph": 12.2,
                "wind_degree": 278,
                "wind_dir": "W",
                "pressure_mb": 1017.0,
                "pressure_in": 30.03,
                "precip_mm": 0.39,
                "precip_in": 0.02,
                "snow_cm": 0.0,
                "humidity": 51,
                "cloud": 77,
                "feelslike_c": 17.0,
                "feelslike_f": 62.7,
                "windchill_c": 17.0,
                "windchill_f": 62.7,
                "heatindex_c": 17.0,
                "heatindex_f": 62.7,
                "dewpoint_c": 6.8,
                "dewpoint_f": 44.2,
                "will_it_rain": 1,
                "chance_of_rain": 100,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 9.0,
                "gust_kph": 14.5,
                "uv": 4.0
            },
            {
                "time_epoch": 1717686000,
                "time": "2024-06-06 16:00",
                "temp_c": 16.2,
                "temp_f": 61.2,
                "is_day": 1,
                "condition": {
                    "text": "Light rain shower",
                    "icon": "//cdn.weatherapi.com/weather/64x64/day/353.png",
                    "code": 1240
                },
                "wind_mph": 8.3,
                "wind_kph": 13.3,
                "wind_degree": 281,
                "wind_dir": "WNW",
                "pressure_mb": 1017.0,
                "pressure_in": 30.04,
                "precip_mm": 0.22,
                "precip_in": 0.01,
                "snow_cm": 0.0,
                "humidity": 56,
                "cloud": 71,
                "feelslike_c": 16.2,
                "feelslike_f": 61.2,
                "windchill_c": 16.2,
                "windchill_f": 61.2,
                "heatindex_c": 16.2,
                "heatindex_f": 61.2,
                "dewpoint_c": 7.6,
                "dewpoint_f": 45.7,
                "will_it_rain": 1,
                "chance_of_rain": 100,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 10.3,
                "gust_kph": 16.6,
                "uv": 4.0
            },
            {
                "time_epoch": 1717689600,
                "time": "2024-06-06 17:00",
                "temp_c": 15.8,
                "temp_f": 60.5,
                "is_day": 1,
                "condition": {
                    "text": "Patchy rain nearby",
                    "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                    "code": 1063
                },
                "wind_mph": 7.6,
                "wind_kph": 12.2,
                "wind_degree": 289,
                "wind_dir": "WNW",
                "pressure_mb": 1017.0,
                "pressure_in": 30.04,
                "precip_mm": 0.08,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 57,
                "cloud": 76,
                "feelslike_c": 15.8,
                "feelslike_f": 60.5,
                "windchill_c": 15.8,
                "windchill_f": 60.5,
                "heatindex_c": 15.8,
                "heatindex_f": 60.5,
                "dewpoint_c": 7.3,
                "dewpoint_f": 45.1,
                "will_it_rain": 1,
                "chance_of_rain": 100,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 9.8,
                "gust_kph": 15.8,
                "uv": 4.0
            },
            {
                "time_epoch": 1717693200,
                "time": "2024-06-06 18:00",
                "temp_c": 15.9,
                "temp_f": 60.6,
                "is_day": 1,
                "condition": {
                    "text": "Patchy rain nearby",
                    "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                    "code": 1063
                },
                "wind_mph": 8.1,
                "wind_kph": 13.0,
                "wind_degree": 294,
                "wind_dir": "WNW",
                "pressure_mb": 1017.0,
                "pressure_in": 30.04,
                "precip_mm": 0.02,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 54,
                "cloud": 53,
                "feelslike_c": 15.9,
                "feelslike_f": 60.6,
                "windchill_c": 15.9,
                "windchill_f": 60.6,
                "heatindex_c": 15.9,
                "heatindex_f": 60.6,
                "dewpoint_c": 6.7,
                "dewpoint_f": 44.1,
                "will_it_rain": 0,
                "chance_of_rain": 61,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 10.3,
                "gust_kph": 16.6,
                "uv": 4.0
            },
            {
                "time_epoch": 1717696800,
                "time": "2024-06-06 19:00",
                "temp_c": 15.1,
                "temp_f": 59.2,
                "is_day": 1,
                "condition": {
                    "text": "Sunny",
                    "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                    "code": 1000
                },
                "wind_mph": 6.9,
                "wind_kph": 11.2,
                "wind_degree": 300,
                "wind_dir": "WNW",
                "pressure_mb": 1018.0,
                "pressure_in": 30.05,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 57,
                "cloud": 17,
                "feelslike_c": 15.1,
                "feelslike_f": 59.2,
                "windchill_c": 15.1,
                "windchill_f": 59.2,
                "heatindex_c": 15.1,
                "heatindex_f": 59.2,
                "dewpoint_c": 6.7,
                "dewpoint_f": 44.1,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 9.6,
                "gust_kph": 15.4,
                "uv": 5.0
            },
            {
                "time_epoch": 1717700400,
                "time": "2024-06-06 20:00",
                "temp_c": 13.6,
                "temp_f": 56.4,
                "is_day": 1,
                "condition": {
                    "text": "Partly Cloudy ",
                    "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                    "code": 1003
                },
                "wind_mph": 5.4,
                "wind_kph": 8.6,
                "wind_degree": 298,
                "wind_dir": "WNW",
                "pressure_mb": 1018.0,
                "pressure_in": 30.07,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 65,
                "cloud": 33,
                "feelslike_c": 13.1,
                "feelslike_f": 55.5,
                "windchill_c": 13.1,
                "windchill_f": 55.5,
                "heatindex_c": 13.6,
                "heatindex_f": 56.4,
                "dewpoint_c": 7.1,
                "dewpoint_f": 44.8,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 8.6,
                "gust_kph": 13.8,
                "uv": 4.0
            },
            {
                "time_epoch": 1717704000,
                "time": "2024-06-06 21:00",
                "temp_c": 12.3,
                "temp_f": 54.2,
                "is_day": 1,
                "condition": {
                    "text": "Partly Cloudy ",
                    "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                    "code": 1003
                },
                "wind_mph": 4.5,
                "wind_kph": 7.2,
                "wind_degree": 286,
                "wind_dir": "WNW",
                "pressure_mb": 1019.0,
                "pressure_in": 30.08,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 72,
                "cloud": 27,
                "feelslike_c": 11.9,
                "feelslike_f": 53.4,
                "windchill_c": 11.9,
                "windchill_f": 53.4,
                "heatindex_c": 12.3,
                "heatindex_f": 54.2,
                "dewpoint_c": 7.4,
                "dewpoint_f": 45.3,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 7.7,
                "gust_kph": 12.5,
                "uv": 4.0
            },
            {
                "time_epoch": 1717707600,
                "time": "2024-06-06 22:00",
                "temp_c": 11.7,
                "temp_f": 53.0,
                "is_day": 0,
                "condition": {
                    "text": "Partly Cloudy ",
                    "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                    "code": 1003
                },
                "wind_mph": 5.1,
                "wind_kph": 8.3,
                "wind_degree": 278,
                "wind_dir": "W",
                "pressure_mb": 1019.0,
                "pressure_in": 30.09,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 74,
                "cloud": 26,
                "feelslike_c": 10.9,
                "feelslike_f": 51.7,
                "windchill_c": 10.9,
                "windchill_f": 51.7,
                "heatindex_c": 11.7,
                "heatindex_f": 53.0,
                "dewpoint_c": 7.2,
                "dewpoint_f": 45.0,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 8.6,
                "gust_kph": 13.9,
                "uv": 1.0
            },
            {
                "time_epoch": 1717711200,
                "time": "2024-06-06 23:00",
                "temp_c": 11.0,
                "temp_f": 51.8,
                "is_day": 0,
                "condition": {
                    "text": "Clear ",
                    "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                    "code": 1000
                },
                "wind_mph": 4.9,
                "wind_kph": 7.9,
                "wind_degree": 277,
                "wind_dir": "W",
                "pressure_mb": 1019.0,
                "pressure_in": 30.09,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 75,
                "cloud": 14,
                "feelslike_c": 10.2,
                "feelslike_f": 50.3,
                "windchill_c": 10.2,
                "windchill_f": 50.3,
                "heatindex_c": 11.0,
                "heatindex_f": 51.8,
                "dewpoint_c": 6.7,
                "dewpoint_f": 44.0,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 8.3,
                "gust_kph": 13.3,
                "uv": 1.0
            }
        ]
    },
    {
        "date": "2024-06-07",
        "date_epoch": 1717718400,
        "day": {
            "maxtemp_c": 18.8,
            "maxtemp_f": 65.8,
            "mintemp_c": 8.2,
            "mintemp_f": 46.7,
            "avgtemp_c": 13.7,
            "avgtemp_f": 56.7,
            "maxwind_mph": 12.3,
            "maxwind_kph": 19.8,
            "totalprecip_mm": 0.56,
            "totalprecip_in": 0.02,
            "totalsnow_cm": 0.0,
            "avgvis_km": 10.0,
            "avgvis_miles": 6.0,
            "avghumidity": 67,
            "daily_will_it_rain": 1,
            "daily_chance_of_rain": 86,
            "daily_will_it_snow": 0,
            "daily_chance_of_snow": 0,
            "condition": {
                "text": "Patchy rain nearby",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                "code": 1063
            },
            "uv": 5.0
        },
        "astro": {
            "sunrise": "04:45 AM",
            "sunset": "09:15 PM",
            "moonrise": "04:45 AM",
            "moonset": "11:07 PM",
            "moon_phase": "Waxing Crescent",
            "moon_illumination": 0,
            "is_moon_up": 0,
            "is_sun_up": 0
        },
        "hour": [
            {
                "time_epoch": 1717714800,
                "time": "2024-06-07 00:00",
                "temp_c": 10.3,
                "temp_f": 50.5,
                "is_day": 0,
                "condition": {
                    "text": "Clear ",
                    "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                    "code": 1000
                },
                "wind_mph": 4.9,
                "wind_kph": 7.9,
                "wind_degree": 273,
                "wind_dir": "W",
                "pressure_mb": 1019.0,
                "pressure_in": 30.1,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 76,
                "cloud": 6,
                "feelslike_c": 9.4,
                "feelslike_f": 48.8,
                "windchill_c": 9.4,
                "windchill_f": 48.8,
                "heatindex_c": 10.3,
                "heatindex_f": 50.5,
                "dewpoint_c": 6.3,
                "dewpoint_f": 43.3,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 8.2,
                "gust_kph": 13.2,
                "uv": 1.0
            },
            {
                "time_epoch": 1717718400,
                "time": "2024-06-07 01:00",
                "temp_c": 9.7,
                "temp_f": 49.5,
                "is_day": 0,
                "condition": {
                    "text": "Clear ",
                    "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                    "code": 1000
                },
                "wind_mph": 4.9,
                "wind_kph": 7.9,
                "wind_degree": 270,
                "wind_dir": "W",
                "pressure_mb": 1019.0,
                "pressure_in": 30.1,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 77,
                "cloud": 4,
                "feelslike_c": 8.7,
                "feelslike_f": 47.6,
                "windchill_c": 8.7,
                "windchill_f": 47.6,
                "heatindex_c": 9.7,
                "heatindex_f": 49.5,
                "dewpoint_c": 5.8,
                "dewpoint_f": 42.5,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 8.1,
                "gust_kph": 13.1,
                "uv": 1.0
            },
            {
                "time_epoch": 1717722000,
                "time": "2024-06-07 02:00",
                "temp_c": 9.1,
                "temp_f": 48.5,
                "is_day": 0,
                "condition": {
                    "text": "Clear ",
                    "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                    "code": 1000
                },
                "wind_mph": 4.5,
                "wind_kph": 7.2,
                "wind_degree": 267,
                "wind_dir": "W",
                "pressure_mb": 1019.0,
                "pressure_in": 30.09,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 76,
                "cloud": 4,
                "feelslike_c": 8.2,
                "feelslike_f": 46.7,
                "windchill_c": 8.2,
                "windchill_f": 46.7,
                "heatindex_c": 9.1,
                "heatindex_f": 48.5,
                "dewpoint_c": 5.2,
                "dewpoint_f": 41.4,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 7.4,
                "gust_kph": 12.0,
                "uv": 1.0
            },
            {
                "time_epoch": 1717725600,
                "time": "2024-06-07 03:00",
                "temp_c": 8.6,
                "temp_f": 47.5,
                "is_day": 0,
                "condition": {
                    "text": "Clear ",
                    "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                    "code": 1000
                },
                "wind_mph": 4.0,
                "wind_kph": 6.5,
                "wind_degree": 257,
                "wind_dir": "WSW",
                "pressure_mb": 1019.0,
                "pressure_in": 30.09,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 77,
                "cloud": 3,
                "feelslike_c": 7.7,
                "feelslike_f": 45.9,
                "windchill_c": 7.7,
                "windchill_f": 45.9,
                "heatindex_c": 8.6,
                "heatindex_f": 47.5,
                "dewpoint_c": 4.8,
                "dewpoint_f": 40.6,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 6.9,
                "gust_kph": 11.1,
                "uv": 1.0
            },
            {
                "time_epoch": 1717729200,
                "time": "2024-06-07 04:00",
                "temp_c": 8.2,
                "temp_f": 46.7,
                "is_day": 0,
                "condition": {
                    "text": "Clear ",
                    "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                    "code": 1000
                },
                "wind_mph": 4.3,
                "wind_kph": 6.8,
                "wind_degree": 244,
                "wind_dir": "WSW",
                "pressure_mb": 1019.0,
                "pressure_in": 30.09,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 78,
                "cloud": 4,
                "feelslike_c": 7.2,
                "feelslike_f": 44.9,
                "windchill_c": 7.2,
                "windchill_f": 44.9,
                "heatindex_c": 8.2,
                "heatindex_f": 46.7,
                "dewpoint_c": 4.5,
                "dewpoint_f": 40.2,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 7.4,
                "gust_kph": 11.8,
                "uv": 1.0
            },
            {
                "time_epoch": 1717732800,
                "time": "2024-06-07 05:00",
                "temp_c": 8.9,
                "temp_f": 48.0,
                "is_day": 1,
                "condition": {
                    "text": "Sunny",
                    "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                    "code": 1000
                },
                "wind_mph": 4.9,
                "wind_kph": 7.9,
                "wind_degree": 249,
                "wind_dir": "WSW",
                "pressure_mb": 1019.0,
                "pressure_in": 30.1,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 75,
                "cloud": 3,
                "feelslike_c": 7.8,
                "feelslike_f": 46.0,
                "windchill_c": 7.8,
                "windchill_f": 46.0,
                "heatindex_c": 8.9,
                "heatindex_f": 48.0,
                "dewpoint_c": 4.8,
                "dewpoint_f": 40.6,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 7.4,
                "gust_kph": 11.9,
                "uv": 3.0
            },
            {
                "time_epoch": 1717736400,
                "time": "2024-06-07 06:00",
                "temp_c": 10.5,
                "temp_f": 50.8,
                "is_day": 1,
                "condition": {
                    "text": "Sunny",
                    "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                    "code": 1000
                },
                "wind_mph": 6.3,
                "wind_kph": 10.1,
                "wind_degree": 242,
                "wind_dir": "WSW",
                "pressure_mb": 1019.0,
                "pressure_in": 30.1,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 70,
                "cloud": 5,
                "feelslike_c": 9.2,
                "feelslike_f": 48.5,
                "windchill_c": 9.2,
                "windchill_f": 48.5,
                "heatindex_c": 10.5,
                "heatindex_f": 50.8,
                "dewpoint_c": 5.2,
                "dewpoint_f": 41.3,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 7.9,
                "gust_kph": 12.7,
                "uv": 4.0
            },
            {
                "time_epoch": 1717740000,
                "time": "2024-06-07 07:00",
                "temp_c": 12.2,
                "temp_f": 53.9,
                "is_day": 1,
                "condition": {
                    "text": "Sunny",
                    "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                    "code": 1000
                },
                "wind_mph": 7.4,
                "wind_kph": 11.9,
                "wind_degree": 244,
                "wind_dir": "WSW",
                "pressure_mb": 1020.0,
                "pressure_in": 30.11,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 64,
                "cloud": 5,
                "feelslike_c": 11.0,
                "feelslike_f": 51.7,
                "windchill_c": 11.0,
                "windchill_f": 51.7,
                "heatindex_c": 12.2,
                "heatindex_f": 53.9,
                "dewpoint_c": 5.5,
                "dewpoint_f": 42.0,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 8.5,
                "gust_kph": 13.7,
                "uv": 4.0
            },
            {
                "time_epoch": 1717743600,
                "time": "2024-06-07 08:00",
                "temp_c": 13.8,
                "temp_f": 56.9,
                "is_day": 1,
                "condition": {
                    "text": "Sunny",
                    "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                    "code": 1000
                },
                "wind_mph": 7.8,
                "wind_kph": 12.6,
                "wind_degree": 248,
                "wind_dir": "WSW",
                "pressure_mb": 1020.0,
                "pressure_in": 30.11,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 58,
                "cloud": 6,
                "feelslike_c": 12.9,
                "feelslike_f": 55.1,
                "windchill_c": 12.9,
                "windchill_f": 55.1,
                "heatindex_c": 13.8,
                "heatindex_f": 56.9,
                "dewpoint_c": 5.6,
                "dewpoint_f": 42.1,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 9.0,
                "gust_kph": 14.5,
                "uv": 4.0
            },
            {
                "time_epoch": 1717747200,
                "time": "2024-06-07 09:00",
                "temp_c": 15.3,
                "temp_f": 59.5,
                "is_day": 1,
                "condition": {
                    "text": "Sunny",
                    "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                    "code": 1000
                },
                "wind_mph": 8.5,
                "wind_kph": 13.7,
                "wind_degree": 251,
                "wind_dir": "WSW",
                "pressure_mb": 1019.0,
                "pressure_in": 30.1,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 52,
                "cloud": 11,
                "feelslike_c": 15.3,
                "feelslike_f": 59.5,
                "windchill_c": 15.3,
                "windchill_f": 59.5,
                "heatindex_c": 15.3,
                "heatindex_f": 59.5,
                "dewpoint_c": 5.4,
                "dewpoint_f": 41.8,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 9.8,
                "gust_kph": 15.7,
                "uv": 5.0
            },
            {
                "time_epoch": 1717750800,
                "time": "2024-06-07 10:00",
                "temp_c": 16.6,
                "temp_f": 61.9,
                "is_day": 1,
                "condition": {
                    "text": "Cloudy ",
                    "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
                    "code": 1006
                },
                "wind_mph": 8.9,
                "wind_kph": 14.4,
                "wind_degree": 249,
                "wind_dir": "WSW",
                "pressure_mb": 1019.0,
                "pressure_in": 30.09,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 48,
                "cloud": 87,
                "feelslike_c": 16.6,
                "feelslike_f": 62.0,
                "windchill_c": 16.6,
                "windchill_f": 62.0,
                "heatindex_c": 16.6,
                "heatindex_f": 62.0,
                "dewpoint_c": 5.6,
                "dewpoint_f": 42.1,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 10.3,
                "gust_kph": 16.6,
                "uv": 4.0
            },
            {
                "time_epoch": 1717754400,
                "time": "2024-06-07 11:00",
                "temp_c": 17.4,
                "temp_f": 63.3,
                "is_day": 1,
                "condition": {
                    "text": "Patchy rain nearby",
                    "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                    "code": 1063
                },
                "wind_mph": 10.1,
                "wind_kph": 16.2,
                "wind_degree": 250,
                "wind_dir": "WSW",
                "pressure_mb": 1019.0,
                "pressure_in": 30.08,
                "precip_mm": 0.01,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 48,
                "cloud": 100,
                "feelslike_c": 17.4,
                "feelslike_f": 63.3,
                "windchill_c": 17.4,
                "windchill_f": 63.3,
                "heatindex_c": 17.4,
                "heatindex_f": 63.3,
                "dewpoint_c": 6.2,
                "dewpoint_f": 43.1,
                "will_it_rain": 0,
                "chance_of_rain": 66,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 11.6,
                "gust_kph": 18.6,
                "uv": 4.0
            },
            {
                "time_epoch": 1717758000,
                "time": "2024-06-07 12:00",
                "temp_c": 16.9,
                "temp_f": 62.4,
                "is_day": 1,
                "condition": {
                    "text": "Overcast ",
                    "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
                    "code": 1009
                },
                "wind_mph": 10.5,
                "wind_kph": 16.9,
                "wind_degree": 251,
                "wind_dir": "WSW",
                "pressure_mb": 1018.0,
                "pressure_in": 30.07,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 50,
                "cloud": 94,
                "feelslike_c": 16.9,
                "feelslike_f": 62.4,
                "windchill_c": 16.9,
                "windchill_f": 62.4,
                "heatindex_c": 16.9,
                "heatindex_f": 62.4,
                "dewpoint_c": 6.5,
                "dewpoint_f": 43.6,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 12.1,
                "gust_kph": 19.5,
                "uv": 4.0
            },
            {
                "time_epoch": 1717761600,
                "time": "2024-06-07 13:00",
                "temp_c": 18.5,
                "temp_f": 65.4,
                "is_day": 1,
                "condition": {
                    "text": "Cloudy ",
                    "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
                    "code": 1006
                },
                "wind_mph": 11.0,
                "wind_kph": 17.6,
                "wind_degree": 246,
                "wind_dir": "WSW",
                "pressure_mb": 1018.0,
                "pressure_in": 30.05,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 46,
                "cloud": 82,
                "feelslike_c": 18.5,
                "feelslike_f": 65.4,
                "windchill_c": 18.5,
                "windchill_f": 65.4,
                "heatindex_c": 18.5,
                "heatindex_f": 65.4,
                "dewpoint_c": 6.6,
                "dewpoint_f": 43.9,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 12.6,
                "gust_kph": 20.3,
                "uv": 4.0
            },
            {
                "time_epoch": 1717765200,
                "time": "2024-06-07 14:00",
                "temp_c": 18.8,
                "temp_f": 65.8,
                "is_day": 1,
                "condition": {
                    "text": "Overcast ",
                    "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
                    "code": 1009
                },
                "wind_mph": 11.4,
                "wind_kph": 18.4,
                "wind_degree": 243,
                "wind_dir": "WSW",
                "pressure_mb": 1017.0,
                "pressure_in": 30.04,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 47,
                "cloud": 100,
                "feelslike_c": 18.8,
                "feelslike_f": 65.8,
                "windchill_c": 18.8,
                "windchill_f": 65.8,
                "heatindex_c": 18.8,
                "heatindex_f": 65.8,
                "dewpoint_c": 7.4,
                "dewpoint_f": 45.2,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 13.1,
                "gust_kph": 21.1,
                "uv": 4.0
            },
            {
                "time_epoch": 1717768800,
                "time": "2024-06-07 15:00",
                "temp_c": 18.3,
                "temp_f": 65.0,
                "is_day": 1,
                "condition": {
                    "text": "Patchy rain nearby",
                    "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                    "code": 1063
                },
                "wind_mph": 12.3,
                "wind_kph": 19.8,
                "wind_degree": 243,
                "wind_dir": "WSW",
                "pressure_mb": 1017.0,
                "pressure_in": 30.02,
                "precip_mm": 0.07,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 53,
                "cloud": 100,
                "feelslike_c": 18.3,
                "feelslike_f": 65.0,
                "windchill_c": 18.3,
                "windchill_f": 65.0,
                "heatindex_c": 18.3,
                "heatindex_f": 65.0,
                "dewpoint_c": 8.7,
                "dewpoint_f": 47.6,
                "will_it_rain": 1,
                "chance_of_rain": 100,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 14.2,
                "gust_kph": 22.8,
                "uv": 4.0
            },
            {
                "time_epoch": 1717772400,
                "time": "2024-06-07 16:00",
                "temp_c": 16.9,
                "temp_f": 62.4,
                "is_day": 1,
                "condition": {
                    "text": "Patchy rain nearby",
                    "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                    "code": 1063
                },
                "wind_mph": 11.9,
                "wind_kph": 19.1,
                "wind_degree": 245,
                "wind_dir": "WSW",
                "pressure_mb": 1017.0,
                "pressure_in": 30.02,
                "precip_mm": 0.12,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 66,
                "cloud": 88,
                "feelslike_c": 16.9,
                "feelslike_f": 62.4,
                "windchill_c": 16.9,
                "windchill_f": 62.4,
                "heatindex_c": 16.9,
                "heatindex_f": 62.4,
                "dewpoint_c": 10.5,
                "dewpoint_f": 50.8,
                "will_it_rain": 1,
                "chance_of_rain": 100,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 14.5,
                "gust_kph": 23.3,
                "uv": 4.0
            },
            {
                "time_epoch": 1717776000,
                "time": "2024-06-07 17:00",
                "temp_c": 17.1,
                "temp_f": 62.8,
                "is_day": 1,
                "condition": {
                    "text": "Patchy rain nearby",
                    "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                    "code": 1063
                },
                "wind_mph": 11.6,
                "wind_kph": 18.7,
                "wind_degree": 244,
                "wind_dir": "WSW",
                "pressure_mb": 1016.0,
                "pressure_in": 30.01,
                "precip_mm": 0.11,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 65,
                "cloud": 90,
                "feelslike_c": 17.1,
                "feelslike_f": 62.8,
                "windchill_c": 17.1,
                "windchill_f": 62.8,
                "heatindex_c": 17.1,
                "heatindex_f": 62.8,
                "dewpoint_c": 10.5,
                "dewpoint_f": 50.9,
                "will_it_rain": 1,
                "chance_of_rain": 100,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 14.2,
                "gust_kph": 22.9,
                "uv": 4.0
            },
            {
                "time_epoch": 1717779600,
                "time": "2024-06-07 18:00",
                "temp_c": 15.9,
                "temp_f": 60.7,
                "is_day": 1,
                "condition": {
                    "text": "Patchy rain nearby",
                    "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                    "code": 1063
                },
                "wind_mph": 11.0,
                "wind_kph": 17.6,
                "wind_degree": 242,
                "wind_dir": "WSW",
                "pressure_mb": 1016.0,
                "pressure_in": 30.01,
                "precip_mm": 0.11,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 73,
                "cloud": 83,
                "feelslike_c": 15.9,
                "feelslike_f": 60.7,
                "windchill_c": 15.9,
                "windchill_f": 60.7,
                "heatindex_c": 15.9,
                "heatindex_f": 60.7,
                "dewpoint_c": 11.2,
                "dewpoint_f": 52.1,
                "will_it_rain": 1,
                "chance_of_rain": 100,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 14.5,
                "gust_kph": 23.3,
                "uv": 4.0
            },
            {
                "time_epoch": 1717783200,
                "time": "2024-06-07 19:00",
                "temp_c": 15.0,
                "temp_f": 59.0,
                "is_day": 1,
                "condition": {
                    "text": "Patchy rain nearby",
                    "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                    "code": 1063
                },
                "wind_mph": 10.3,
                "wind_kph": 16.6,
                "wind_degree": 234,
                "wind_dir": "SW",
                "pressure_mb": 1016.0,
                "pressure_in": 30.01,
                "precip_mm": 0.05,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 77,
                "cloud": 50,
                "feelslike_c": 15.0,
                "feelslike_f": 59.0,
                "windchill_c": 15.0,
                "windchill_f": 59.0,
                "heatindex_c": 15.0,
                "heatindex_f": 59.0,
                "dewpoint_c": 11.1,
                "dewpoint_f": 52.0,
                "will_it_rain": 1,
                "chance_of_rain": 100,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 13.9,
                "gust_kph": 22.3,
                "uv": 4.0
            },
            {
                "time_epoch": 1717786800,
                "time": "2024-06-07 20:00",
                "temp_c": 13.8,
                "temp_f": 56.8,
                "is_day": 1,
                "condition": {
                    "text": "Patchy rain nearby",
                    "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                    "code": 1063
                },
                "wind_mph": 9.2,
                "wind_kph": 14.8,
                "wind_degree": 233,
                "wind_dir": "SW",
                "pressure_mb": 1016.0,
                "pressure_in": 30.01,
                "precip_mm": 0.07,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 83,
                "cloud": 71,
                "feelslike_c": 12.6,
                "feelslike_f": 54.6,
                "windchill_c": 12.6,
                "windchill_f": 54.6,
                "heatindex_c": 13.8,
                "heatindex_f": 56.8,
                "dewpoint_c": 11.0,
                "dewpoint_f": 51.7,
                "will_it_rain": 1,
                "chance_of_rain": 100,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 13.6,
                "gust_kph": 21.9,
                "uv": 3.0
            },
            {
                "time_epoch": 1717790400,
                "time": "2024-06-07 21:00",
                "temp_c": 13.0,
                "temp_f": 55.4,
                "is_day": 1,
                "condition": {
                    "text": "Partly Cloudy ",
                    "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                    "code": 1003
                },
                "wind_mph": 8.1,
                "wind_kph": 13.0,
                "wind_degree": 235,
                "wind_dir": "SW",
                "pressure_mb": 1016.0,
                "pressure_in": 30.01,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 87,
                "cloud": 39,
                "feelslike_c": 11.8,
                "feelslike_f": 53.3,
                "windchill_c": 11.8,
                "windchill_f": 53.3,
                "heatindex_c": 13.0,
                "heatindex_f": 55.4,
                "dewpoint_c": 10.9,
                "dewpoint_f": 51.7,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 12.5,
                "gust_kph": 20.2,
                "uv": 4.0
            },
            {
                "time_epoch": 1717794000,
                "time": "2024-06-07 22:00",
                "temp_c": 12.5,
                "temp_f": 54.5,
                "is_day": 0,
                "condition": {
                    "text": "Partly Cloudy ",
                    "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                    "code": 1003
                },
                "wind_mph": 7.4,
                "wind_kph": 11.9,
                "wind_degree": 246,
                "wind_dir": "WSW",
                "pressure_mb": 1016.0,
                "pressure_in": 30.0,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 85,
                "cloud": 27,
                "feelslike_c": 11.4,
                "feelslike_f": 52.5,
                "windchill_c": 11.4,
                "windchill_f": 52.5,
                "heatindex_c": 12.5,
                "heatindex_f": 54.6,
                "dewpoint_c": 10.1,
                "dewpoint_f": 50.2,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 11.7,
                "gust_kph": 18.8,
                "uv": 1.0
            },
            {
                "time_epoch": 1717797600,
                "time": "2024-06-07 23:00",
                "temp_c": 12.2,
                "temp_f": 53.9,
                "is_day": 0,
                "condition": {
                    "text": "Partly Cloudy ",
                    "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                    "code": 1003
                },
                "wind_mph": 7.4,
                "wind_kph": 11.9,
                "wind_degree": 253,
                "wind_dir": "WSW",
                "pressure_mb": 1016.0,
                "pressure_in": 30.0,
                "precip_mm": 0.0,
                "precip_in": 0.0,
                "snow_cm": 0.0,
                "humidity": 82,
                "cloud": 39,
                "feelslike_c": 11.0,
                "feelslike_f": 51.7,
                "windchill_c": 11.0,
                "windchill_f": 51.7,
                "heatindex_c": 12.2,
                "heatindex_f": 53.9,
                "dewpoint_c": 9.2,
                "dewpoint_f": 48.6,
                "will_it_rain": 0,
                "chance_of_rain": 0,
                "will_it_snow": 0,
                "chance_of_snow": 0,
                "vis_km": 10.0,
                "vis_miles": 6.0,
                "gust_mph": 11.5,
                "gust_kph": 18.6,
                "uv": 1.0
            }
        ]
    }
]